import { ProjectState } from "../enums/project-status.enum";
import { Process } from "./process";
import { Milestone } from "./milestone";
import { SimplePhase } from "./simplePhase";
import { HistoryLog } from "./historyLog";
import { PmcProperty } from "./pmcProperty";

export class Project {
    public guid: number;
    public version: number;
    public projectId: string;
    public tag: string[];
    public title: string;
    public status: ProjectState;
    public priority: number;
    public refObjectIdName: string;
    public refObjectType: string;
    public projectType: string;
    public projectTypeIdName: string;
    public subType: string;
    public dueDate: string;
    public pmcProjectType: any;
    public subtype: string;
    public parents: Project[];
    public children: Project[];
    public processes: Process[];
    public customerProjectId: number;
    public ownerId: number;
    public details: string;
    public guStatus: string;
    public comment: string;
    public risk: number;
    public refObjectId: number;
    public milestones: Milestone[];
    public phases: SimplePhase[];
    public history: HistoryLog[];
    public displayMetaInfo: string;
    public properties: PmcProperty[];
    public propertiesMap: Map<string, any>;
    public milestonesMap: Map<string, any>;
    public createDate: string;
    public createUser: number;
    public ownerName: string;
    public updateDate: string;
    public updateUser: number;
    public parentIds: number[];
    public childrenIds: number[];
    public additionalInfo: Map<string, any>;
    public resultStatus: string;
    public resultComment: string;
    public authBase: string;
    public running: boolean;
    public humanReadableId: string;
}
