export class ProjectType {
    public guid: number;
    public idName: string;
    public name: string;
    public docuConfigs: any;
    public allowedTags: string;
    public allowedProcesses: any;
    public readRights: string;
    public writeRights: string;
    public createRights: string;
    public deleteRights: string;
    public readRightGroups: string[];
    public writeRightGroups: string[];
    public createRightGroups: string[];
    public deleteRightGroups: string[];
    public allowedTagList: string[];
    public processDefinitions: any[];
    public allowedSubTypes: string;
    public allowedSubtypeList: string[];
    public startProcess: string;
    public allowedMilestones: any[];
    public objectType: string;
    public additionalProperties: any;
    public configuration: string;
    public phases: any[];
    public detailsTemplate: string;
    public propertiesTemplate: string;
    public creationPropertiesTemplate: string;
}