import { AppSettings } from '@alanda/common';

export const ALANDA_CONFIG: AppSettings = {
  API_ENDPOINT: '/alanda-rest/app',
  DATE_FORMAT: 'yyyy-MM-dd',
  DATE_FORMAT_PRIME: 'yy-mm-dd',
  LOCALE_PRIME: {
    firstDayOfWeek: 1,
    dayNames: [
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ],
    dayNamesShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    monthNames: [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ],
    monthNamesShort: [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ],
    today: 'Today',
    clear: 'Clear',
    dateFormat: 'yy-mm-dd',
    weekHeader: 'Wk',
  },
  AVATAR_BASE_PATH: 'src/app/assets',
  AVATAR_EXT: 'jpg',
  /* WEBSOCKET_ENDPOINT : 'ws://localhost:8080/pmc-rest/websockets', */
};
